In [3]:
import pandas as pd                             # imports

path = "./CMO-Historical-Data-Annual.xlsx"      # path to dataset

data = pd.read_excel(path,sheet_name=1)         # initalizing the data

In [5]:
name_row = data.iloc[5:6]
attribute_row = data.iloc[6:7]

name_row

some_list = []

for i in name_row:
    column = f"""{name_row[i].values[0]} {attribute_row[i].values[0]}"""
    some_list.append(column)

some_list[0] = "Year"


df = data
df.columns = some_list
df = df.iloc[7:]
df.set_index("Year", inplace=True)

In [7]:
df

,"Crude oil, average ($/bbl)","Crude oil, Brent ($/bbl)","Crude oil, Dubai ($/bbl)","Crude oil, WTI ($/bbl)","Coal, Australian ** ($/mt)","Coal, South Afican ** ($/mt)","Natural gas, US ($/mmbtu)","Natural gas, Europe ($/mmbtu)","Liquefied natural gas, Japan ($/mmbtu)",Natural gas index (2010=100),...,Aluminum ($/mt),"Iron ore, cfr spot ($/dmtu)",Copper ($/mt),Lead ($/mt),Tin ($/mt),Nickel ($/mt),Zinc ($/mt),Gold ($/troy oz),Platinum ($/troy oz),Silver ($/troy oz)
Year,,,,,,,,,,,,,,,,,,,,,
1960,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,…,...,511.471832,11.42,678.755833,198.85,2196.733333,1631,246.191667,35.27,83.5,0.9137
1961,1.57,1.57,1.57,…,…,…,0.15,0.404774,…,…,...,511.471832,11.02,633.084167,176.975,2449.891667,1711,214.308333,35.25,83.5,0.924442
1962,1.52,1.52,1.52,…,…,…,0.16,0.404774,…,…,...,498.060392,11.01,645.143333,155.283333,2471.383333,1761,185.925,35.23,83.5,1.083725
1963,1.5,1.5,1.5,…,…,…,0.16,0.391351,…,…,...,498.795265,11.02,645.950833,174.808333,2507.733333,1741.666667,211.508333,35.09,80.930833,1.279108
1964,1.45,1.45,1.45,…,…,…,0.15,0.38415,…,…,...,525.985631,10.24,969.753333,277.883333,3412.741667,1741.666667,326.491667,35.1,88.480833,1.293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,61.4075,64.031667,63.1775,57.013333,77.885833,71.941667,2.565883,4.802351,10.564302,61.145976,...,1794.488333,93.849167,6010.145,1996.5075,18661.156667,13913.908333,2550.41,1392.498333,863.989167,16.217583
2020,41.257778,42.3,42.165,39.308333,60.785,65.656667,2.014375,3.242024,8.313348,45.506044,...,1703.986667,108.918333,6173.770833,1824.880833,17124.599167,13787.256667,2266.449167,1770.254167,883.393333,20.536583
2021,69.070556,70.443333,68.805,67.963333,138.05,119.840229,3.851408,16.115878,10.761649,130.67448,...,2472.848333,161.71,9317.05,2200.365,32384.148333,18464.965833,3002.520833,1799.629167,1091.133333,25.164583
2022,97.101389,99.824167,97.049167,94.430833,344.893333,240.556977,6.368317,40.340157,18.426925,281.59297,...,2705.019167,121.300833,8822.365833,2150.5975,31335.405,25833.725,3481.378333,1800.6025,961.715833,21.794417
2023,80.755694,82.61625,81.981667,77.669167,172.779167,119.105758,2.537808,13.113403,14.234563,102.802142,...,2255.739167,120.574167,8490.290833,2135.7975,25938.113333,21521.115,2652.604167,1942.665833,966.355,23.398583

In [22]:
print(f"""
{df.columns.get_loc("Banana, US ($/kg)")}
{df.columns.get_loc("Sugar, world ($/kg)")}
      """)

food_df = df.iloc[:, 36:44]
food_df

36
44

,"Banana, US ($/kg)",Orange ($/kg),Beef ** ($/kg),Chicken ** ($/kg),Lamb ** ($/kg),"Shrimps, Mexican ($/kg)","Sugar, EU ($/kg)","Sugar, US ($/kg)"
Year,,,,,,,,
1960,0.142868,0.129983,0.736533,0.30013,…,1.605698,0.122356,0.125847
1961,0.134922,0.133008,0.68195,0.312279,…,1.693883,0.124341,0.125663
1962,0.13139,0.108008,0.714125,0.319562,…,2.252387,0.126325,0.128419
1963,0.144083,0.094008,0.666342,0.328029,…,1.997018,0.126766,0.165898
1964,0.170408,0.084,0.840883,0.337631,…,1.8133,0.126582,0.138707
...,...,...,...,...,...,...,...,...
2019,1.140546,0.560006,4.76366,1.998396,8.103142,12.601057,0.365668,0.576729
2020,1.21633,0.602985,4.667309,1.631694,7.831025,12.673074,0.372711,0.59466
2021,1.205479,0.65259,5.34241,1.991483,11.548567,13.699049,0.386476,0.740146
2022,1.488922,0.919285,5.621643,1.683158,11.94055,13.514321,0.344235,0.787729
2023,1.59657,1.574127,4.902952,1.533279,9.93761,10.186888,0.353262,0.894929